# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [pull_request_target]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
   list:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: matheuspiment/list-pr-files@v1.0.0
        with:
          ghToken: ${{ github.token }}
